### RUN ON: 
# Push to main branch (after PR merge).

### JOBS:
# Generate and upload build files.
# Push build files to S3.
# Invalidate CloudFront distribution cache

name: 'Deploy Application'
on:
  push:
    branches:
      - main
    paths-ignore: 
      - ".github/workflows/*"
      - ".husky/**"
      - "public/**"
      - ".gitignore"
      - "README.md"

  workflow_dispatch: 

jobs:
  create_dist:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Cache deps
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: deps-node-module-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install deps
        run: npm ci

      - name: Create dist
        env:
          VITE_ASSETS_URL: ${{ vars.VITE_ASSETS_URL }}
        run: npm run build
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Remove stale dist
        run: |
          aws s3 rm s3://${{ secrets.S3_BUCKET }}/ --recursive

      - name: Upload all except HTML w/1-yr cache policy
        run: |
          aws s3 cp ./dist/ s3://${{ secrets.S3_BUCKET }}/ --exclude "*.html" --cache-control "max-age=31536000, immutable" --recursive

      - name: Upload HTML w/no-cache policy
        run: |
          aws s3 cp ./dist/ s3://${{ secrets.S3_BUCKET }}/ --exclude "*" --include "*.html" --cache-control no-cache --recursive
      
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
      

